### ISSUE TITLE
Apple! I have a question.

### ISSUE THREAD

**Issue by jdongel2004** [TesseractTeam-v2/Tesseract#1]
#### OS and versions

* Tesseract:
* PHP:
* Server OS:
* Game version: 
* Server host:
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```
Will you fix the Linux error? or just backup?

**Comment by AppleDevelops** [comment]
What error?

**Comment by jdongel2004** [comment]
./bin/php7/bin/php: error while loading shared libraries: libltdl.so.7: cannot open shared object file: No such file or directory

My mistake? Will replacing bin files.. I can solve the problem..?

**Comment by AppleDevelops** [comment]
It's a PHP binaries issue.
