### ISSUE TITLE
(SUGGESTION)

### ISSUE THREAD

**Issue by junkdude** [TesseractTeam-v2/Tesseract#15]
Tesseract:Latest
PHP:7.0.16
Server OS:Linux, Debian
Game version: from 1.0.5 to 1.0.9
Server Local

Instead of making a new branch, could you fork pmmp for stability and implement the features in that branch?

**Comment by NFGamerMC** [comment]
This is not the true nature of Tesseract, try to keep suggestions down in the issues, just DM @AppleDevelops or PM him in the Forums

**Comment by NFGamerMC** [comment]
@AppleDevelops Can you close this.
